services:
  l8tesearch:
    image: l8tenever/l8tesearch:latest
    build: .
    container_name: l8tesearch
    ports:
      - "9999:9999"
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
